# config hyper-parameters here concerning a training trial

# [model]
# supported models (case-insensitive):
# 'acfnet', 'att2scale', 'bisenet', 'danet', 'deeplabv3', 'deeplabv3plus', 'denseaspp',
# 'fcn', 'ladder', 'pspnet', 'seenet', 'swiftnet', 'swiftnetpr', 'semanticfpn',
# 'canet', 'eprnet'
model_name: pspnet
backbone: resnet101
backbone_pretrain: True
norm: sbn
aux: True
aux_weight: 0.4
resume: ~
lr_mult: 1
dilate: True

# [dataset]
# supported dataset (case-insensitive):
# 'ade20k', 'COCO', 'VOC2012', 'SBD', 'VOCAug', 'PContext', 'SUNRGBD', 'NYU', 'SiftFlow',
# 'Stanford', 'aeroscapes', 'cityscapes', 'CamVid', 'CamVidFull', 'GATECH', 'Mapillary',
# 'BDD', 'KITTIZhang', 'KITTIXu', 'KITTIRos', 'MHPv1'
data_name: ade20k
crop_size: 576
base_size: 640

# [optimizer]
# supported optimizers: 'sgd', 'nag', 'adam'
# supported learning rate scheduler: 'poly', 'cosine', 'constant', 'step', 'linear'
lr: 0.01
target_lr: 0
wd: 1.e-4
momentum: 0.9
optimizer: sgd
lr_scheduler: poly
poly:
  power: 0.9
step:
  step_factor: 0.5
  step_epoch:
    - 5
adam:
  adam_beta1: 0.9
  adam_beta2: 0.999

# [training]
epochs: 120
bs_train: 16
bs_val: 32