wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.13
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.2
    t:
      1:
      - 5
      2:
      - 5
      4: 3.6.2
      5: 0.10.13
adam:
  desc: null
  value:
    adam_beta1: 0.9
    adam_beta2: 0.999
aux:
  desc: null
  value: false
aux_weight:
  desc: null
  value: null
backbone:
  desc: null
  value: resnet18
backbone_init:
  desc: null
  value:
    manner: cls
    backbone_ckpt: null
base_size:
  desc: null
  value: 2048
bs_train:
  desc: null
  value: 8
bs_val:
  desc: null
  value: 16
crop_size:
  desc: null
  value: 1024
ctx:
  desc: null
  value:
  - gpu(4)
  - gpu(5)
  - gpu(6)
  - gpu(7)
data_name:
  desc: null
  value: Cityscapes
dilate:
  desc: null
  value: false
epochs:
  desc: null
  value: 240
lr:
  desc: null
  value: 0.01
lr_mult:
  desc: null
  value: 1
lr_scheduler:
  desc: null
  value: poly
model_name:
  desc: null
  value: bisenet
momentum:
  desc: null
  value: 0.9
norm:
  desc: null
  value: sbn
num_train:
  desc: null
  value: 3475
num_valid:
  desc: null
  value: 500
optimizer:
  desc: null
  value: sgd
poly:
  desc: null
  value:
    power: 0.9
resume:
  desc: null
  value: null
start_time:
  desc: null
  value: '20210303_125312'
step:
  desc: null
  value:
    step_epoch:
    - 5
    step_factor: 0.5
target_lr:
  desc: null
  value: 0
wd:
  desc: null
  value: 0.0001
