wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.13
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      4: 3.7.9
      5: 0.10.13
adam:
  desc: null
  value:
    adam_beta1: 0.9
    adam_beta2: 0.999
aux:
  desc: null
  value: false
aux_weight:
  desc: null
  value: null
backbone:
  desc: null
  value: resnet101
backbone_init:
  desc: null
  value:
    manner: cls
    backbone_ckpt: null
base_size:
  desc: null
  value: 640
bs_train:
  desc: null
  value: 16
bs_val:
  desc: null
  value: 32
criterion:
  desc: null
  value: gluoncv.loss.MixSoftmaxCrossEntropyLoss
crop_size:
  desc: null
  value: 480
ctx:
  desc: null
  value:
  - gpu(0)
  - gpu(1)
  - gpu(2)
  - gpu(3)
data_name:
  desc: null
  value: nyuv2
dilate:
  desc: null
  value: true
epochs:
  desc: null
  value: 180
lr:
  desc: null
  value: 0.01
lr_mult:
  desc: null
  value: 1
lr_scheduler:
  desc: null
  value: poly
model_name:
  desc: null
  value: pspnet
momentum:
  desc: null
  value: 0.9
norm:
  desc: null
  value: sbn
num_train:
  desc: null
  value: 795
num_valid:
  desc: null
  value: 654
optimizer:
  desc: null
  value: sgd
poly:
  desc: null
  value:
    power: 0.9
resume:
  desc: null
  value: null
start_time:
  desc: null
  value: '20210428_120848'
step:
  desc: null
  value:
    step_epoch:
    - 5
    step_factor: 0.5
target_lr:
  desc: null
  value: 0
wd:
  desc: null
  value: 0.0001
